### ISSUE TITLE
`numpy`'s and `torch`'s functions are suddenly treated as typos

### ISSUE THREAD

**Issue by Borda** [crate-ci/typos#969]
Another case is when we see an increase in detected typos, but not sure if they shall be treated as typos...
```yaml
  - repo: https://github.com/crate-ci/typos
    rev: v1.20.0
    hooks:
      - id: typos
```
gives following 
```
error: `arange` should be `arrange`
  --> src/torchmetrics/functional/retrieval/precision_recall_curve.py:89:22
   |
89 |         topk = torch.arange(1, max_k + 1, device=preds.device)
   |                      ^^^^^^
   |
error: `arange` should be `arrange`
  --> tests/unittests/image/test_psnr.py:55:44
   |
55 |         batch = np.moveaxis(batch, dim, np.arange(-num_dims, 0))
   |                                            ^^^^^^
   |
error: `arange` should be `arrange`
```
see full log [here](https://results.pre-commit.ci/run/github/323721661/1712009049.zNUzw5a4Ram0WUkyHUzRiA)

**Comment by tlambert03** [comment]
from here: https://github.com/crate-ci/typos/pull/957/files#diff-d7206c435daafa1b53ca9227408de1a1b8c199cb61b5a21973add69b14afd5caR4219

**Comment by epage** [comment]
Should be fixed in 1.20.3 which is building release binaries

**Comment by my1e5** [comment]
@epage On `v1.22.0`, this is still failing when I use `np.arange` in a code block within my documentation markdown files.
For example if I have a `.md` file within `docs/`
```markdown
# Example markdown file

This file includes a code block

'''py
foo = np.arange(0,100,1)
'''
```
(Pretend the `'''` in the above example are ` ``` `)

This line gets changed to `np.arrange`.

**Comment by epage** [comment]
We limited the fix to just Python files.

We do not have syntax-aware spell checking which means we cannot tell when one file type is embedded in another file type. Even if we did, it would be reasonable to refer to a symbol with `arrange` and would then need to deal with that somehow as well.

**Comment by darosio** [comment]
This is now back in jupyther notebook (ipynb) files where cells containing np.arange() become np.arrange()
